# Generated by Django 4.1.7 on 2023-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Good'), (4, 'Great'), (5, 'Amazing')], null=True),
        ),
    ]
