# Generated by Django 4.1.7 on 2023-03-25 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'pending'), ('D', 'denied'), ('E', 'expired'), ('A', 'approved'), ('CA', 'cancel approved'), ('CD', 'cancel_denied'), ('CP', 'cancel pending'), ('T', 'terminated'), ('CO', 'completed')], default='P', max_length=2)),
                ('price', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='property.property')),
            ],
        ),
    ]
