# Generated by Django 4.1.7 on 2023-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyamenities',
            name='amenity',
            field=models.CharField(blank=True, choices=[('Pool', 'Pool'), ('Wi-Fi', 'Wi-Fi'), ('Air Conditioning', 'Air Conditioning'), ('Heating', 'Heating'), ('Pets Allowed', 'Pets Allowed'), ('Washer and Dryer', 'Washer and Dryer'), ('Jacuzzi', 'Jacuzzi'), ('Free Parking', 'Free Parking'), ('Equipped Kitchen', 'Equipped Kitchen'), ('Fireplace', 'Fireplace')], max_length=30),
        ),
    ]
