# Generated by Django 4.1.7 on 2023-03-25 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Good'), (4, 'Great'), (5, 'Amazing')])),
                ('receiver_id', models.PositiveIntegerField()),
                ('rater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiver_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reservation.reservation')),
            ],
        ),
    ]
